import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Truculenta } from 'next/font/google';

const truculenta = Truculenta({
  variable: '--font-truclenta',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${truculenta.variable}`}>
        {children}
      </body>
    </html>
  );
}
